### ISSUE TITLE
Exception loading graph in SharedArrayBasedDirectedGraph

### ISSUE THREAD

**Issue by plofgren** [twitter/cassovary#188] opened 2015-06-23 19:45 UTC
Today when I was loading a simple graph into SharedArrayBasedDirectedGraph, I received an ArrayIndexOutOfBoundsException.  The graph is [here](https://github.com/plofgren/cassovary/blob/load-bug/cassovary-core/src/test/resources/graphs/test_graph.txt) and a minimal main class demonstrating the error is [here](https://github.com/plofgren/cassovary/blob/load-bug/cassovary-core/src/main/scala/LoadBugMain.scala).  The stack trace is below.  I just pulled the current version of cassovary, and my scala version is 2.11.6.
When I change `reader.toSharedArrayBasedDirectedGraph` to `reader.toArrayBasedDirectedGraph` the graph loads correctly.  I'll switch to using ArrayBasedDirectedGraph, but I wanted to report this in case someone can see what causes this and help others avoid this.

Thanks!

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphCo$$$$308510d7b33aba1419de2daaa79926$$$$nonfun$8$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$6.apply$mcVI$sp(SharedArrayBasedDirectedGraph.scala:278)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphCo$$$$308510d7b33aba1419de2daaa79926$$$$nonfun$8$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$6.apply(SharedArrayBasedDirectedGraph.scala:276)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphCo$$$$308510d7b33aba1419de2daaa79926$$$$nonfun$8$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$6.apply(SharedArrayBasedDirectedGraph.scala:276)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:234)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$com$twitter$cassovary$graph$SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$fillInEdges$1$1$$anonfun$8$$anonfun$apply$15$$anonfun$apply$16.apply(SharedArrayBasedDirectedGraph.scala:275)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$com$twitter$cassovary$graph$SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$fillInEdges$1$1$$anonfun$8$$anonfun$apply$15$$anonfun$apply$16.apply(SharedArrayBasedDirectedGraph.scala:274)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at com.twitter.cassovary.util.io.AdjacencyListGraphReader$OneShardReader$$anon$1.foreach(AdjacencyListGraphReader.scala:79)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.twitter.cassovary.util.io.AdjacencyListGraphReader$OneShardReader.foreach(AdjacencyListGraphReader.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at com.twitter.cassovary.util.io.AdjacencyListGraphReader$OneShardReader.map(AdjacencyListGraphReader.scala:74)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$com$twitter$cassovary$graph$SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$fillInEdges$1$1$$anonfun$8$$anonfun$apply$15.apply(SharedArrayBasedDirectedGraph.scala:273)
	at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$com$twitter$cassovary$graph$SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$fillInEdges$1$1$$anonfun$8$$anonfun$apply$15.apply(SharedArrayBasedDirectedGraph.scala:273)
	at com.twitter.util.Try$.apply(Try.scala:13)
	at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:112)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pankajgupta** [comment] 2015-06-23 22:21
I'm looking at this

**Comment by pankajgupta** [comment] 2015-06-23 23:14
Can reproduce the bug when the stored graph dir is desired to be BothInOut.

**Comment by szymonm** [comment] 2015-06-24 01:48
Did you find the cause, Pankaj? If not, I can have a look at it.

**Comment by pankajgupta** [comment] 2015-06-24 17:43
Thanks Szymon. I didn't get a chance to get deeper yet. Please feel free to
take a look

Feel free to work on branch 'issue188' that has the following two files to
help reproduce/debug the error.

$ git diff --name-only master
cassovary-core/src/test/resources/graphs/toy_9nodes.txt
cassovary-examples/src/main/scala/HelloLoadSharedGraph.scala

**Comment by pankajgupta** [comment] 2015-06-29 16:43
Fixed by @szymonm

**Closed by pankajgupta** 2015-06-29 16:43 UTC
